includes_dir: .jekyll/includes
sass:
  sass_dir: .jekyll/sass

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed

include: []

exclude:
  - README.md
  - .github

permalink: none
remote_theme: just-the-docs/just-the-docs

# Default config: https://github.com/just-the-docs/just-the-docs/blob/main/_config.yml
url: https://tools.adoyle.me
# baseurl: /
title: ADoyle 的工具箱
description: 只记录我在用的工具。持续更新中。
logo: https://media.githubusercontent.com/media/adoyle-h/_imgs/master/assets/logo.png
favicon_ico: ./.jekyll/assets/favicon.ico
footer_content:
  Copyright 2016-2023 ADoyle (adoyle.h@gmail.com). Some Rights Reserved.<br>
  The project is licensed under <b>BSD 3-clause License</b>.
aux_links_new_tab: true # Makes Aux links open in a new tab. Default is false
aux_links:
  "Give Me a Github Star":
    - https://github.com/adoyle-h/my-development-tools
last_edit_timestamp: true
color_scheme: dark
back_to_top: true
back_to_top_text: ⬆ 返回顶部

search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
